# Generated by Django 6.0.4 on 2026-05-04 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactenquiry',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['service_name']},
        ),
        migrations.AlterModelOptions(
            name='serviceprice',
            options={'ordering': ['-created_at']},
        ),
    ]
