# Generated by Django 6.0.4 on 2026-05-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_alter_contactenquiry_options_alter_gallery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ladiesmeasurement',
            name='photo_back',
            field=models.ImageField(blank=True, null=True, upload_to='measurements/ladies/', verbose_name='Back Photo'),
        ),
        migrations.AddField(
            model_name='ladiesmeasurement',
            name='photo_front',
            field=models.ImageField(blank=True, null=True, upload_to='measurements/ladies/', verbose_name='Front Photo'),
        ),
        migrations.AddField(
            model_name='ladiesmeasurement',
            name='photo_side',
            field=models.ImageField(blank=True, null=True, upload_to='measurements/ladies/', verbose_name='Side Photo'),
        ),
        migrations.AddField(
            model_name='menmeasurement',
            name='photo_back',
            field=models.ImageField(blank=True, null=True, upload_to='measurements/men/', verbose_name='Back Photo'),
        ),
        migrations.AddField(
            model_name='menmeasurement',
            name='photo_front',
            field=models.ImageField(blank=True, null=True, upload_to='measurements/men/', verbose_name='Front Photo'),
        ),
        migrations.AddField(
            model_name='menmeasurement',
            name='photo_side',
            field=models.ImageField(blank=True, null=True, upload_to='measurements/men/', verbose_name='Side Photo'),
        ),
    ]
