# Generated by Django 6.0.4 on 2026-05-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_ladiesmeasurement_photo_back_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['full_name']},
        ),
        migrations.AlterModelOptions(
            name='ladiesmeasurement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='menmeasurement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
